# Generated by Django 2.1 on 2018-08-02 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20180802_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialtest',
            name='event',
        ),
        migrations.RemoveField(
            model_name='userspecialtest',
            name='specialtest',
        ),
        migrations.RemoveField(
            model_name='userspecialtest',
            name='user',
        ),
        migrations.DeleteModel(
            name='SpecialTest',
        ),
        migrations.DeleteModel(
            name='UserSpecialTest',
        ),
    ]
