# Generated by Django 2.1 on 2018-08-02 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20180802_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userevent',
            name='event',
        ),
        migrations.RemoveField(
            model_name='userevent',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='age_on_event_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='ama_number',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='bike_displacement',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='bike_make',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='confirmation',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
        migrations.AddField(
            model_name='profile',
            name='omra_number',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='rider_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='start_time',
            field=models.TimeField(blank=True, max_length=300, null=True),
        ),
        migrations.DeleteModel(
            name='UserEvent',
        ),
    ]
