# Generated by Django 2.1 on 2018-08-02 21:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0004_auto_20180802_2125'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='RiderProfile',
        ),
    ]
