# Generated by Django 2.1 on 2018-08-03 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20180802_2127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riderprofile',
            old_name='confirmation',
            new_name='confirmation_number',
        ),
        migrations.AlterField(
            model_name='riderprofile',
            name='bike_make',
            field=models.CharField(blank=True, choices=[('ALT', 'Alta'), ('ATK', 'ATK'), ('Bet', 'Beta'), ('Can', 'Can-Am'), ('CZ', 'CZ'), ('Gas', 'Gas Gas'), ('Hbg', 'Husaberg'), ('Hon', 'Honda'), ('Hus', 'Husqvarna'), ('Kaw', 'Kawasaki'), ('KTM', 'KTM'), ('Mai', 'Maico'), ('Mon', 'Montesa'), ('Sco', 'Scorpa'), ('Suz', 'Suzuki'), ('TM', 'TM'), ('Yam', 'Yamaha'), ('N/A', 'Not Listed')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='riderprofile',
            name='state',
            field=models.CharField(blank=True, choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], max_length=2, null=True),
        ),
    ]
