# Generated by Django 2.1 on 2018-08-03 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20180803_0231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riderprofile',
            name='emergency_contact_contact',
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='am_time_est',
            field=models.TimeField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=models.DateField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='pro_time_est',
            field=models.TimeField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='riderprofile',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='riderprofile',
            name='address_line_two',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='riderprofile',
            name='ama_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='riderprofile',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='riderprofile',
            name='confirmation_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='riderprofile',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='riderprofile',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='riderprofile',
            name='omra_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='riderprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='riderprofile',
            name='start_time',
            field=models.TimeField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='riderprofile',
            name='zip_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
