# Generated by Django 2.1 on 2018-08-04 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20180803_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderprofile',
            name='bike_make',
            field=models.CharField(blank=True, choices=[('ALT', 'Alta'), ('ATK', 'ATK'), ('Bet', 'Beta'), ('Can', 'Can-Am'), ('CZ', 'CZ'), ('Gas', 'Gas Gas'), ('Hbg', 'Husaberg'), ('Hon', 'Honda'), ('Hus', 'Husqvarna'), ('Kaw', 'Kawasaki'), ('KTM', 'KTM'), ('Mai', 'Maico'), ('Mon', 'Montesa'), ('Sco', 'Scorpa'), ('Suz', 'Suzuki'), ('TM', 'TM'), ('Yam', 'Yamaha'), ('N/A', 'Not Listed')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='riderprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
