# Generated by Django 2.1 on 2018-08-04 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20180804_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderprofile',
            name='Registration_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
