# Generated by Django 2.1 on 2018-08-04 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_riderprofile_registration_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riderprofile',
            name='event',
        ),
    ]
