# Generated by Django 2.1 on 2018-08-04 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_riderprofile_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riderprofile',
            old_name='Registration_date',
            new_name='Registration_date_time',
        ),
    ]
