# Generated by Django 2.1 on 2018-08-05 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_auto_20180804_2300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='riderprofile',
            old_name='rider',
            new_name='user',
        ),
    ]
