# Generated by Django 2.1 on 2018-08-05 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_auto_20180804_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderprofile',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.Event'),
        ),
    ]
