# Generated by Django 2.1 on 2018-08-05 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_auto_20180804_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderprofile',
            name='user',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
