# Generated by Django 2.1 on 2018-08-08 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0033_auto_20180808_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='map_location',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
