# Generated by Django 2.1 on 2018-08-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0034_auto_20180808_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='entry_closes',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='post_entry_cost',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='pre_entry_cost',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='slogan',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
