# Generated by Django 2.1 on 2018-08-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0035_auto_20180808_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_details',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
