# Generated by Django 2.0.7 on 2018-08-10 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0036_auto_20180808_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderprofile',
            name='conf_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
