# Generated by Django 2.0.7 on 2018-08-10 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0037_riderprofile_conf_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riderprofile',
            name='conf_timestamp',
        ),
    ]
