# Generated by Django 2.1 on 2018-08-14 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0040_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bike_displacement',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bike_make',
        ),
        migrations.AddField(
            model_name='profile',
            name='escort_rider',
            field=models.BooleanField(default=False),
        ),
    ]
