# Generated by Django 2.1 on 2018-08-14 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0041_auto_20180814_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='escort_rider',
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='escort_rider',
            field=models.BooleanField(default=False),
        ),
    ]
