# Generated by Django 2.1 on 2018-08-14 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0042_auto_20180814_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riderprofile',
            name='escort_rider',
        ),
    ]
