# Generated by Django 2.1 on 2018-08-14 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0043_remove_riderprofile_escort_rider'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='rider_limit',
            field=models.IntegerField(blank=True, max_length=30, null=True),
        ),
    ]
