# Generated by Django 2.1 on 2018-08-14 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0044_event_rider_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='rider_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
