# Generated by Django 2.1 on 2018-08-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0046_auto_20180815_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderprofile',
            name='rider_class',
            field=models.CharField(choices=[('Expert Schedule Classes - Over age 16', 'Expert Schedule Classes - Over age 16'), ('Expert Schedule Classes - 16 and under', 'Expert Schedule Classes - 16 and under'), ('Amateur Schedule Classes - Over age 16', 'Amateur Schedule Classes - Over age 16'), ('Expert Schedule Classes - 16 and under', 'Expert Schedule Classes - 16 and under'), ('Class 60 and 70 Rider', 'Class 60 and 70 Rider'), ('Escort Rider', 'Escort Rider')], max_length=100),
        ),
    ]
