# Generated by Django 2.1 on 2018-08-17 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0047_auto_20180817_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='escort_rider_cost',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
