# Generated by Django 2.1 on 2018-08-17 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0048_event_escort_rider_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='escort_rider_cost',
            field=models.IntegerField(max_length=4),
        ),
        migrations.AlterField(
            model_name='event',
            name='post_entry_cost',
            field=models.IntegerField(max_length=4),
        ),
        migrations.AlterField(
            model_name='event',
            name='pre_entry_cost',
            field=models.IntegerField(max_length=4),
        ),
    ]
