# Generated by Django 2.1 on 2018-08-18 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0052_auto_20180817_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_details',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
