# Generated by Django 2.1 on 2018-08-28 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0053_auto_20180817_1846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ama_number',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='omra_number',
            field=models.CharField(blank=True, max_length=300, null=True, unique=True),
        ),
    ]
