# Generated by Django 2.1 on 2018-08-28 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0054_auto_20180827_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ama_number',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='omra_number',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='riderprofile',
            name='registration_date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
