# Generated by Django 2.1 on 2018-08-28 03:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0055_auto_20180827_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderprofile',
            name='registration_date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 8, 27, 20, 32, 28, 19978), null=True),
        ),
    ]
